[env]
SQLITE_DB_FILE = "monirail.sqlite"
RAILWAY_API_URL = "https://backboard.railway.app/graphql/v2"

[tools]
node = "lts"
dprint = "latest"

[tasks."setup"]
description = "Setup the project"
run = ["npm install"]
outputs = ["node_modules", "package-lock.json"]
sources = ["src/*.ts", "package.json"]

[tasks."build"]
description = "Build the project"
run = ["mise run generate", "npm exec -- tsup src/index.ts"]

[tasks."generate"]
description = "Generate GraphQL types"
run = ["npm exec -- graphql-codegen", "mise run format"]

[tasks."format"]
description = "Format code"
run = "dprint fmt"

[tasks."check:format"]
description = "Check formatting"
run = "dprint check"

[tasks."check:lint"]
description = "Statically analyze the code for issues"
run = "npm exec -- tsc --noEmit --incremental --tsBuildInfoFile .typescript/tsconfig.tsbuildinfo"

[settings]
activate_aggressive = true
experimental = true
yes = true
